// LUNEXA v5 — cartpage.js
document.addEventListener('DOMContentLoaded',()=>{renderCartPage();});
function renderCartPage(){
  const items=Cart.getAll(),container=document.getElementById('cart-items'),summaryEl=document.getElementById('cart-summary'),emptyEl=document.getElementById('empty-cart');
  if(!items.length){if(container)container.innerHTML='';if(emptyEl)emptyEl.style.display='flex';if(summaryEl)summaryEl.innerHTML='';return;}
  if(emptyEl)emptyEl.style.display='none';
  const subtotal=Cart.getTotal(),shipping=subtotal>999?0:99,tax=Math.round(subtotal*.18),total=subtotal+shipping+tax;
  if(container)container.innerHTML=items.map(item=>{const p=getProductById(item.productId);if(!p)return'';return`<div class="cart-item"><a href="product.html?id=${p.id}" class="cart-item-img-link"><img src="${p.image}" alt="${p.name}" loading="lazy" onerror="this.src='https://picsum.photos/seed/ln${p.id}/200/200'"/></a><div><div class="cart-item-category">${p.category}</div><a href="product.html?id=${p.id}" class="cart-item-name">${p.name}</a><div class="cart-item-unit-price">${formatPrice(p.price)} each</div></div><div class="cart-item-controls"><div class="cart-qty-controls"><button onclick="Cart.updateQty(${p.id},${item.quantity-1});renderCartPage();">−</button><span class="cart-qty-val">${item.quantity}</span><button onclick="Cart.updateQty(${p.id},${item.quantity+1});renderCartPage();">+</button></div><div class="cart-item-line-total">${formatPrice(p.price*item.quantity)}</div><button class="cart-remove-btn" onclick="Cart.remove(${p.id});renderCartPage();"><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="3 6 5 6 21 6"/><path d="M19 6l-1 14H6L5 6"/></svg>Remove</button></div></div>`;}).join('');
  if(summaryEl)summaryEl.innerHTML=`<h2 class="summary-title">Order Summary</h2><div class="summary-lines"><div class="summary-line"><span>Subtotal (${Cart.getCount()} items)</span><span>${formatPrice(subtotal)}</span></div><div class="summary-line"><span>Delivery</span><span>${shipping===0?'<span class="free-label">FREE</span>':formatPrice(shipping)}</span></div>${subtotal>0&&subtotal<999?`<div class="free-ship-notice">🚚 Add ${formatPrice(999-subtotal)} more for free delivery</div>`:''}<div class="summary-line"><span>GST (18%)</span><span>${formatPrice(tax)}</span></div></div><div class="summary-divider"></div><div class="summary-total-line"><span>Total</span><span>${formatPrice(total)}</span></div><a href="checkout.html" class="btn-checkout" onclick="if(!Store.isLoggedIn()){event.preventDefault();showAuthGate('checkout');return;}"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>Proceed to Checkout</a><a href="products.html" class="btn-continue-shopping">← Continue Shopping</a><div class="cart-trust"><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="11" width="18" height="11" rx="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/></svg>Secure checkout · SSL encrypted</div>`;
}
